# SPDX-License-Identifier: MIT

name: Lint GitHub Actions workflows
on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash

      - name: Check workflow files
        env:
          SHELLCHECK_OPTS: --exclude=SC2193,SC2001,SC2086
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash