# SPDX-License-Identifier: MIT
name: Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    uses: ./.github/workflows/build.yml

  deployRelease:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages & GitHub
    steps:
      - name: Pull down the build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact-name }}
          run-id: ${{ needs.build.outputs.artifact-id }}

      - name: Publish a new production release on Cloudflare
        uses: cloudflare/wrangler-action@v3
        id: cloudflare-publish
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy --project-name ${{ vars.CLOUDFLARE_PROJECT_NAME }} --branch production --commit-hash ${{ github.sha }} --commit-msg "${{ github.event.head_commit.message }}" --commit-dirty=true

      - name: Make a Github Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          make_latest: true
          fail_on_unmatched_files: true
          files: |
            sbom.spdx.json
            ${{ needs.build.outputs.artifact-name }}.zip