# SPDX-License-Identifier: MIT
name: Build & Publish PR to Cloudflare

on:
  pull_request:
    types: [ opened, reopened, ready_for_review, synchronize ]
jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pull-requests: write

    outputs:
      artifact-id: ${{ steps.upload.outputs.artifact-id }}
      d_version: ${{ steps.vars.outputs.d_version }}

    steps:
      - name: Pull down the build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact-name }}
          run-id: ${{ needs.build.outputs.artifact-id }}

      - name: Move the sbom into the webroot
        run: mv ${{ steps.vars.outputs.sbom_path }} ${{ github.workspace }}/build/client/

      # Use the old action because the new one doesn't support getting the url output yet
      # https://github.com/cloudflare/wrangler-action/issues/300
      - name: Publish PR to Cloudflare
        uses: cloudflare/pages-action@v1
        id: cloudflare-publish
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          directory: build/client

      - name: Add a PR comment with the deploy URI
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            🚀 This branch can be previewed at ${{ steps.cloudflare-publish.outputs.url }}